### ISSUE TITLE
return a tx receipt from CheckTx/AppendTx

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#109]
Return https://github.com/eris-ltd/eris-db/blob/develop-tmsp/rpc/core/types/responses.go#L102 and 
https://github.com/eris-ltd/eris-db/blob/develop-tmsp/tmsp/erisdb.go#L145
ought to return https://github.com/eris-ltd/eris-db/blob/develop-tmsp/rpc/core/types/responses.go#L102
so that https://github.com/eris-ltd/eris-db/blob/develop-tmsp/rpc/test/tests.go#L81 works.

Note the receipt used to be generated in the broadcast_tx rpc function itself (https://github.com/eris-ltd/tendermint/blob/develop/rpc/core/mempool.go#L29) but broadcast_tx is now going to be something that happens on tendermint's end, so won't necessarily have access to that unless it's returned as data or log in the TMSP response. alternatively, if we keep broadcast_tx in eris_db, it could happen in broadcast_tx, but the erisdb tmsp app would be more useful if it returned this data itself

**Comment by silasdavis** [comment]
Picking this up
