### ISSUE TITLE
Disconnect continuous integration and continuous deployment cycles

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#112]
1. Specific interest is to allow pull requests to run through CI without initiating a deployment cycle; external PRs are currently failing over docker login depending on private login details

https://github.com/eris-ltd/eris-db/blob/develop/circle.yml#L20

2. look at integrating the work done in eris-marmont to be integrated in the deployment cycle

**Comment by AFDudley** [comment]
Okay, this relates to some of my other tickets, so I will start on it now.

**Comment by compleatang** [comment]
closing this ticket as this is well covered by more precise tickets and the Jenkins Epic.
