### ISSUE TITLE
Revert deprecation of Send and SendAndHold in Eris-DB 0.12.0 staging

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#115]
Eris-DB methods `Send` and `SendAndHold` have been deprecated, only keeping `Transact` and `TransactAndHold`, in develop-tmsp (staging branch for 0.12.0).

@dennismckinnon @NodeGuy might want to object; if so we will revert.

@ebuchman equally interested to hear the argument for deprecation.

**Comment by compleatang** [comment]
is this done?

**Comment by NodeGuy** [comment]
I object because I'm [using Send in slam-a-chain](https://github.com/eris-ltd/hello-eris/blob/60d13b332cb362036b63bb2b9bd48b5ca92a7ab2/benchmarks/slam_a_chain/lib/index.js#L111).

**Comment by silasdavis** [comment]
This was reintroduced, closing.
