### ISSUE TITLE
ecm should be able to start erisdb or tendermint

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#12]
erisdb needs a --fast-sync flag too

**Comment by androlo** [comment]
might be other flags needed too i guess. eris-db doesn't have a system for flags yet. all it does is take a path to the database folder as argument. i'll schedule an update once we've discussed what will be needed (thinking especially about eris-cli).

**Comment by hughht5** [comment]
was this ever implemented? It takes a long time for a node to catch up currently.

**Comment by compleatang** [comment]
yes it has been implemented. check the `config.toml` for your chain (in ~/.eris/chains/chainname/config.toml) make sure that the `fast_sync` field is true.

If you do not have a config.toml in ~/.eris/chains/chainname then just copy the config from ~/.eris/chains/default/config.toml and make the change. Next time you run "new" it'll catch up faster.

If you'd like to change it for a running chain, stop the chain, then `eris chains exec chainName -i` (that will enter you into a bash shell "inside the chain's" containers). From there edit ~/.eris/chainName/config.toml and `exit`. After you exit out of the shell restart the chain and things should catch up faster.
