### ISSUE TITLE
GetBlocks fails to return blocks

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-db#120]
`http://192.168.99.100:35320/blockchain/blocks` returns

```
{"min_height":382,"max_height":0,"block_metas":[]}
```

The **Example Queries** from [the documentation](https://github.com/eris-ltd/eris-db/blob/master/api.md#getblocks) also yield no results:

`http://192.168.99.100:35320/blockchain/blocks?q=height:>4` returns

```
{"min_height":287,"max_height":5,"block_metas":[]}
```

`http://192.168.99.100:35320/blockchain/blocks?q=height:10..*` returns

```
{"min_height":279,"max_height":10,"block_metas":[]}
```

No matter what query I chose, `block_metas` is always empty.

This has been reported by two users as well: https://github.com/eris-ltd/eris-db.js/issues/32 and https://support.erisindustries.com/discussions/topics/6000034973.

**Comment by benjaminbollen** [comment]
@NodeGuy can I close this issue ?

**Comment by ebuchman** [comment]
I fixed this here: https://github.com/eris-ltd/eris-db/tree/fix_get_blocks

Never heard back about it. Probably should get merged in.

**Comment by NodeGuy** [comment]
No, please don't close the issue until the bug is fixed!

**Comment by benjaminbollen** [comment]
I did review it, and looks good to me, and I can merge it in.

**Comment by benjaminbollen** [comment]
@NodeGuy can you confirm this branch fixes the problem, or shall I?

**Comment by NodeGuy** [comment]
This is bug prevents basic advertised functionality from working and should have been caught by an automated test before it got to customers.

Please write an automated test for the `GetBlocks` feature such that CircleCI doesn't approve the build unless it passes.

**Comment by benjaminbollen** [comment]
I fully agree.  The work we are putting into eris-db is precisely to make it possible to define different areas of unit testing on the rpc (and interface to you).  This should have been done already obviously.

**Comment by TheBlockchainGuy** [comment]
Hello,
I'm using erisbd-0.12.0 and still encountering the problem of empty block_metas. Is this problem fixed and how can I get the fix please ?

**Comment by benjaminbollen** [comment]
@TheBlockchainGuy we tested and merged this hotfix on master; so in a couple of minutes the fix is pushed out and having eris pull the latest docker images should give you access to this fix.  Sorry this was pushed down the road and thanks for reminding us.

**Comment by TheBlockchainGuy** [comment]
Ok, thank you.
I downgraded to 0.11.4 because .12 is not stable enough yet. When it's done, would I get the fix after an "eris init" and could you please add a comment here to say it's done ?

**Comment by TheBlockchainGuy** [comment]
Hello,
Is this bug fixed ? if not, are there any workaround ?

**Comment by benjaminbollen** [comment]
this has been fixed and merged into master.  If it does not work for you, please report it.

**Comment by compleatang** [comment]
If you'd like to use the fix currently on master with 0.11.4 we think it will work (although we do not test this). 

To try it run 

```
docker pull quay.io/eris/erisdb:0.12.0-rc2
docker tag quay.io/eris/erisdb:0.12.0-rc2 quay.io/eris/erisdb:0.11.4
```

**Comment by TheBlockchainGuy** [comment]
Yes it works with 0.11.4. Thank you guys.

**Comment by TheBlockchainGuy** [comment]
Casey,
When I did "docker tag ..." in my local/root machine, and the deployed locally the chain, my GetBlocks service did worked but when I deployed the chain to a remote docker-machine it looks like it's using the old erisdb:0.11.4. Do you confirm this behaviour and how to get the fix for my remote machines ?

**Comment by benjaminbollen** [comment]
This fix should be in 0.12.0-rc2 as well; so you can use latest master; that probably makes it easier to make sure the remote machines have the right build.  Let us know if you find problems.

**Comment by compleatang** [comment]
@TheBlockchainGuy so the images that you have on one machine are entirely confined to that machine and that machine only. So you'll have to perform the above sequence for each of the docker-machines you are trying to utilize. To do this first you bring a machine "in scope"  with the following line:

```bash
eval "$(docker-machine env $machine)"
```

After the machine is in scope then rerun the above pull and tag command. Repeat as necessary for each of the machines.

**Comment by TheBlockchainGuy** [comment]
OK, I did it and it worked (via docker-machine env).
I agree with benjamin to use the last version. Is this 0.12.0-rc2 stable enough (I've had troubles with the 0.12.0 couple of weeks ago) ?

**Comment by benjaminbollen** [comment]
depends on your requirements; I would still recommend 0.11.4 if you want the (most) stable release;  You'll be missing the latest advances, but 0.11 is most battle tested, and 0.12 is a moving target.
