### ISSUE TITLE
resolve extra file for arm

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-db#139]
see #137 for more info. requires consideration of int/uint

**Comment by benjaminbollen** [comment]
also, arm support (above patch on blockchain.go in #137 ) will get lost when we move the re-organised code; so this is a reminder to port it over;

**Comment by zramsay** [comment]
hopefully we'll have test for ARM support by then

**Comment by compleatang** [comment]
is this (now) a dupe of #251 ?

**Comment by silasdavis** [comment]
Yes, closing.
