### ISSUE TITLE
want to verify sig inside contract; ecrecover not possible

### ISSUE THREAD

**Issue by aubreychen** [eris-ltd/eris-db#146]
I would like to be able to do signature verification inside a smart contract so that I do not have to trust outside oracles.

From my understanding, Eris uses a different key type than Ethereum so the solidity ecrecover function will never work with an Eris key.

Requesting that a custom native contract be added implementing the signature verification as a native contract so that the public key can be recovered from a signature.

**Comment by compleatang** [comment]
closing in favor of #190 please follow along there @aubreychen
