### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [eris-ltd/eris-db#148]
Is it possible to license the product suit under a more permissive license?

**Comment by compleatang** [comment]
Hello there. Thanks for the question. We have spent many hours considering the pros and cons of various open source licenses and are satisfied with our current licensing posture. 

We have detailed our posture and thinking [here](https://db.erisindustries.com/products/2015/08/30/on-licensing/) if you would like to dig into our reasoning.
