### ISSUE TITLE
[RPC] `/healthz` endpoint - define introspective health check endpoint - "Yes, I'm alive!"

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-db#153]
Related to: https://github.com/eris-ltd/eris-cli/issues/984

The idea is an endpoint that performs a bunch of health checks and returns `ok` or `!ok`. It's supposed to be an emerging standard for golang/anylang APIs but maybe isn't picking up

**Comment by silasdavis** [comment]
Sorry @zramsay :) cruel to be kind, please reopen if you have more information.

**Comment by zramsay** [comment]
it's for https://github.com/eris-ltd/eris-cli/issues/984
The idea is an endpoint that performs a bunch of health checks and returns `ok` or `!ok`. It's supposed to be an emerging standard for golang/anylang APIs but maybe isn't picking up

**Comment by silasdavis** [comment]
This is an interesting idea. There is an emerging theme of work around system observability. One way to frame system health is by implementing metrics and remote tracing and setting metrics remotely to define 'healthy'. This may be complementary to this where the node itself has built-in understanding of its health. Though it needs to be able to introspect that information.

It could be convenient for health check endpoint when being managed behind a load balancer like those provided by AWS

**Comment by zramsay** [comment]
handled by https://github.com/eris-ltd/eris/issues/1011
