### ISSUE TITLE
Upgrade existing chains to single configuration file and configure for single data directory

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#155]
1. Eris-DB v0.11.4 and prior read `config.toml` by Tendermint and `server_conf.toml` by Eris-DB; as of 0.12.0-rc2 Eris-DB reads a single `server_config.toml`
2. As of Eris-DB v0.12.0rc2 the state database is (by default) separated from the consensus engine block store; but on existing chains (Eris-DB v0.11.4) these files are in the same directory; make sure Eris-DB v0.12.0 configures itself for a single shared directory for existing chains.

**Comment by silasdavis** [comment]
I note playing with latest eris-db out of a container the default is to look for a 'config.toml'.

Are there any tickets for CLI to integrate with the new config of eris-db. Presumably this will involve copying a server config file into the chain dir? Perhaps I've missed conversations about this but was just wondering. @benjaminbollen

**Comment by compleatang** [comment]
Definitely. CLI side discussion here -> 

https://github.com/eris-ltd/eris-cli/issues/336
https://github.com/eris-ltd/eris-cli/issues/651
https://github.com/eris-ltd/eris-cli/issues/899

**Comment by VoR0220** [comment]
Epic time?
