### ISSUE TITLE
Reimplement functionality to load and register chain from/on etcb

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#163]
for reference of deleted dead code on 0.12.0:
https://github.com/eris-ltd/eris-db/blob/4fc4fab54e2a9f6c2e1cbcabf00adf8d08f08a7a/DOCKER/chain_register.sh

**Comment by silasdavis** [comment]
@benjaminbollen please reopen if you think I'm being too hasty. I think this is interesting, but I am not sure how helpful it is to have it as an issue. This is certainly in the collective consciousness, perhaps a wiki or document could store this or an RFC. I am tending towards keeping only actionable issues open.
