### ISSUE TITLE
Eris client tooling

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#178]
Mint client tooling has different targets that relate either to client side functionality or server side functionality:

| mint-client | client side | server side | other |
| --- | --- | --- | --- |
| mintx | eris-client tx |  |  |
| mintinfo | eris-client status |  |  |
| mintconfig |  |  | eris-cm make |
| mintperms | eris-client perm |  |  |
| mintsync |  | eris-db sync |  |
| mintdump |  | eris-db dump |  |
| mintkey | eris-client key |  |  |
| mintunsafe |  |  |  |

**Comment by compleatang** [comment]
:+1: this may be closed no?
