### ISSUE TITLE
How to send transaction to a deployed contract with eris-db

### ISSUE THREAD

**Issue by getsachmail** [eris-ltd/eris-db#179]
We are able to call deployed contrat's method using eris-contract, as well as we are able to call transaction, blockchain other eris-db functions. Do we need to send transaction using eris-db.txt().transact() method to deployed contract or calling contract's method using eris-contract automatically create a transaction.

**Comment by dennismckinnon** [comment]
Hello thank you for the question. The preferred method of calling the function in a contract is via the function attached to the contract object in eris contracts as this will automatically format the transaction according to the contract's abi and erisdb will not. For example if your contract has a function MyFunc(arg, arg2). And you got a contract object either from the .new or .at functions then contract.MyFunc(arg, arg2, callback(err, data)) would be the correct way to call it. You can also use contract.MyFunc.sendTransaction(...) to ensure you form a transaction as opposed to a query which would be contract.MyFunc.query(arg...). The difference between these two is that in a query no transaction is formed. The transaction is only simulated. This means that no state change will occur.

I hope this helped clear things up.

**Comment by getsachmail** [comment]
Thx for quick response, yes it helped.

Regard
Sachin

On 27-Jul-2016 11:28 PM, "Dennis Mckinnon" <notifications@github.com> wrote:
>
> Hello thank you for the question. The preferred method of calling the
function in a contract is via the function attached to the contract object
in eris contracts as this will automatically format the transaction
according to the contract's abi and erisdb will not. For example if your
contract has a function MyFunc(arg, arg2). And you got a contract object
either from the .new or .at functions then contract.MyFunc(arg, arg2,
callback(err, data)) would be the correct way to call it. You can also use
contract.MyFunc.sendTransaction(...) to ensure you form a transaction as
opposed to a query which would be contract.MyFunc.query(arg...). The
difference between these two is that in a query no transaction is formed.
The transaction is only simulated. This means that no state change will
occur.

**Comment by getsachmail** [comment]
Contract
contract ChainCoin {    
    event Send(address from, address to, uint value);
    function send(address receiver, uint amount) {
        receiver.send(amount);
        Send(msg.sender, receiver, msg.value);
    }    
}

can you please help me with parameters

e.g.
ChainCoinObj.Send.sendTransaction(receiver, amount ,{from: '0x036a03fc47084741f83938296a1c8ef67f6e34fa', to: '0xa8ade7feab1ece71446bed25fa0cf6745c19c3d5', value: web3.toWei(1, "ether")}))

**Comment by getsachmail** [comment]
Do we need to send PrivateKey to sendTransaction method?
