### ISSUE TITLE
Disentangle docker builds

### ISSUE THREAD

**Issue by androlo** [eris-ltd/eris-db#18]
I don't think this is a hurry, and as far as I know everyone's fine with this as a temp solution. Can't see any problems with this as of now, except from what i understand its a bit unconventional. Adding the issue nonetheless.

Would it be good to keep a tendermint fork in our repos later, or maybe just a tag in the main repo that all our current and coming tools can refer to? Just as a way to ensure that we keep everything the same.  Gonna bring this up on some meeting.

**Comment by compleatang** [comment]
tag's would be a good idea. for docker the key will be having an automated way for circle to build the docker images such that the tenderment which is put in godeps is and compiled into the erisdb binary is the same commit (or tag, either fine) as is compiled into the tendermint binary (both of which should be available to the docker image, which may be unconventional, but adds lots of flexibility for us).

**Comment by androlo** [comment]
no need to track this. it's solving itself.
