### ISSUE TITLE
Allow terser erisdb logging levels to allow `docker logs` and `eris chains logs` in follow mode

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-db#180]
- The `eris chains logs -f` command chokes on the erisdb output (issue [#612](https://github.com/eris-ltd/eris-cli/issues/612)) in the logs follow mode. Allow more terser (the tersest possible) output mode retaining transaction information to be controllable on the cli side with a flag.

**Comment by silasdavis** [comment]
In hand with: #343
