### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [eris-ltd/eris-db#194]
Is it possible to switch Eris product range to a more permissive license like ASL 2.0?

**Comment by zramsay** [comment]
duplicate of #148; eris-db will remain GPL3 for the foreseeable future. Please see [this post](https://db.erisindustries.com/products/2015/08/30/on-licensing/) for our rationale.

**Comment by zramsay** [comment]
@sirinath you'll be glad to hear we've relicensed to Apache 2:
https://github.com/eris-ltd/eris-db/blob/master/license.md
