### ISSUE TITLE
[Tests] Implement unit tests for CheckTx and AppendTx in /consensus/tendermint

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#223]
Run integration tests for in-process tendermint as consumer unit tests in /consensus/tendermint asserting advertised behaviour from Tendermint

**Comment by compleatang** [comment]
is this staying in 0.12.0 and/or done? or are we moving to 0.12.1|0.16.0?

**Comment by silasdavis** [comment]
I'm a little unclear exactly what this is asking for

**Comment by benjaminbollen** [comment]
To be done, and it is super, crystal clear :)

**Comment by silasdavis** [comment]
Let me point out the bit that is unclear:
>Run integration tests for in-process tendermint as consumer unit tests in /consensus/tendermint asserting advertised behaviour from Tendermint

**Comment by silasdavis** [comment]
Closing this in favour of #405 and #406
