### ISSUE TITLE
Accounts.genPrivAccount don't broadcast the new account created.

### ISSUE THREAD

**Issue by Fukunaga42** [eris-ltd/eris-db#227]
[ 1.12.0] docker version
    [ 0.12.0] eris version
    [1.6 ] go version
    [ 0.7.0] docker-machine version
    [ ubuntu 14.04]

Hi,
I have 3 validator node running, and one root node on this instance:
When I run genPrivAccount() from eris-db.js I have a good return value of the new generated account, but when i look on the accounts on my blockchain this new account never appear.

Here's my script and the result:
```
var edbFactory = require('eris-db');
chainUrl = 'http://0.0.0.0:1337/rpc';
var accounts = require('./accounts.json');
var edb = edbFactory.createInstance(chainUrl);
edb.start(function(result, error) {
          if (!error){
              console.log("eris-db success -> ", result);
          } else
              console.log(error);
})

var myAccount = edb.accounts();
myAccount.genPrivAccount(accounts.devchain_root_000, function(error, result){
       if (!error){
               console.log('result = ', result);
//                res.json({ message: 'Account created!', privKey: '', pubKey: '', address: '' })    ;
       }
})
```

```
result =  { address: '438D7B22DD3CBC82AA5C20938511605802D815C3',
 pub_key:
  [ 1,
    '788326B40466160AE728DBB1CE684C3D47E39F532817048C268E8316F9EA2F02' ],
 priv_key:
  [ 1,
    '2D0626D7094AEFD37D8EF21CC8931F01D5C49E52301EA702ED1A7A619EF4D683788326B40466160AE728DBB1CE684C3D47E39F532817048C268E8316F9EA2F02' ] }
```

**Comment by benjaminbollen** [comment]
Thanks @Fukunaga42 

I opened a mirror issue in eris-db.js, where it should be discussed first: https://github.com/eris-ltd/eris-db.js/issues/36

We can keep both issues to track the solution on both sides of the connection.

**Comment by NodeGuy** [comment]
@dennismckinnon What's the expected behavior here?  Are we confusing users by not explaining that they need to send ether to the new account?

**Comment by Fukunaga42** [comment]
@NodeGuy  Hi, yes the confusion come from this page:
https://docs.erisindustries.com/tutorials/advanced/chain-maintaining/
on the "Maintenance Task 1: Adding Actors" Part
You run ` eris keys gen` and you run `mintx permission set_base` on the new address generated, and the result seems to be that the new adress is deploy on the blockchain.

**Comment by silasdavis** [comment]
I'm closing this as I think it should be addressed by a rework of the docs: https://github.com/eris-ltd/monax.io/issues/118
