### ISSUE TITLE
[Consensus] Update tendermint engine to 0.7.x

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#236]
- [ ] Tendermint has moved from to 0.7
- [x] deprecate `TENDERMINT_VERSION = 0.5.0` as now unused
- [x] assert on `eris-db-<semver>` from config file

**Comment by benjaminbollen** [comment]
#240 deprecates TENDERMINT_VERSION = 0.5.0

**Comment by zramsay** [comment]
we're beyond this
