### ISSUE TITLE
Need Functionality for Delegate Call

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-db#244]
Currently the develop branch is missing a critical opcode that the solidity compiler uses when talking to libraries, and that opcode is called DelegateCall. I have put in a PR for it over in #243 but it is not complete and there is functionality for it that can be found fairly easily in the go-ethereum space (I can't seem to translate the stack language atm so I'll leave that to you two unless you have ideas for me to contribute). https://github.com/ethereum/go-ethereum/search?utf8=%E2%9C%93&q=delegatecall

**Comment by benjaminbollen** [comment]
fixed in #261 on develop
fixed in #247 on master
