### ISSUE TITLE
[RPC] Js Libs cause edb to `panic`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#252]
Currently all clients of the edb rpc need to be able to query the chain-id that the node is running. Before we ship 0.12.0 we need this line implemented... https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/pipe.go#L104

In preliminary testing, changing it to something like the below cured the panic.

```go
	blockchain := newBlockchain(moduleConfig.ChainId, moduleConfig.GenesisFile, (BlockStore)(nil))
```

**Comment by silasdavis** [comment]
This falls under an existing epic
