### ISSUE TITLE
List hotfixes that went into master; but need to be carried over on develop

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#259]
- [x] metablock #120 
- [x] delegate call #244 #247; see #261 
- [x] nested factory generation is not persisted #164
- [x] please append ...

**Comment by benjaminbollen** [comment]
Nested account generation is fixed on 0.12.0-rc3 https://github.com/eris-ltd/eris-db/blob/develop/manager/eris-mint/evm/vm.go#L849

**Comment by benjaminbollen** [comment]
metablock issue ported over in : https://github.com/eris-ltd/eris-db/pull/322

**Comment by compleatang** [comment]
this can be closed, no?
