### ISSUE TITLE
[Client] list needs for eris-pm

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#264]
expose rpc calls through eris-client library
- [x] call, callcode (which will be renamed to QueryContract and QueryContractCode)
- [x] LatestBlockHeight

please append here more notes as needed; closing #256 and #257 as result

**Comment by benjaminbollen** [comment]
- [ ] GetChainId (for a given ChainName)

**Comment by VoR0220** [comment]
- [ ] List validators
- [ ] Rebond, Bond, Unbond
- [ ] Permissions

**Comment by benjaminbollen** [comment]
https://github.com/eris-ltd/eris-db/pull/187#discussion-diff-78937360R191

**Comment by silasdavis** [comment]
@benjaminbollen is this still serving a purpose please reopen with information for the uninitiated
