### ISSUE TITLE
[Eris-Client] Bytecode X deployed at address Y, Block Z

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-db#265]
Problem: Verification in Eris-PM, down the line, how do we ensure that these values are in Block X at the specified address. This is critical for contract verification. 

Solution: Simple function that returns whether or not bytecode X was deployed at address Y, Block Z for this chain.

**Comment by benjaminbollen** [comment]
Why does it matter which blockheight the values were changed in; also pretty sure that that information is already accessible with some work, but just looking for some more context.

**Comment by VoR0220** [comment]
Verify that youre working on the proper contract.

**Comment by VoR0220** [comment]
That the bytecode deployed at address x at block y was this bytecode is very useful for formal verification.

**Comment by compleatang** [comment]
Get block at height X, Get address and done. This is pms job to orchestrate not clients'. Client isn't built to give every single helper needed to do the things. It is built to provide a low level golang access to DBs functionality. Some processing and further calling is almost always required. But those will need to happen at the pm level or wherever the library is being used.
