### ISSUE TITLE
Suppress logging of non-transaction blocks option

### ISSUE THREAD

**Issue by alist** [eris-ltd/eris-db#27]
I run ```erisdb ~/.eris/data/alistFirstID``` and non-transaction blocks flood my terminal output. They make it hard to locate logs for my transactions.

I would like a logging verbosity option that would suppress output from any block that has zero transactions.

**Comment by androlo** [comment]
This is being worked on in Tendermint, which is the actual blockchain client. Right now theyr'e adding new log levels but I can't say for sure when it will be committed (you may have noticed other things as well, such as VM dumps that can't be filtered at all). Leaving this open.

**Comment by ebuchman** [comment]
This happens through app/core separation and tmsp
