### ISSUE TITLE
I can't figure out how to start.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-db#33]
> The recommended way of working with eris-db is through eris-cli (develop branch as of now).

OK, I installed eris-cli and read its ginormous README.

Now, on to using it.

> The simplest way to get started is by simply running $ erisdb.

```shell
$ erisdb
bash: erisdb: command not found
```

OK, looks like we're missing a step here.  Perhaps erisdb is a "service"?

```shell
$ eris services known
ipfs
keys
```

Nope.

Is it a "chain"?

```shell
$ eris chains known

bash-3.2$
```

Guess not.

Wearing my hat of curious developer I'm losing interest.  We need a smoother on-ramp.

**Comment by androlo** [comment]
Yes. That was written when eris-cli was still pre 0.10. I'll update. Probably just put a series of commands there.

**Comment by androlo** [comment]
wow... that is a hefty readme.. also looks like much of it isn't even on usage. Either way, I'll add a few lines in the eris-cli portion. simple step-by-step instructions on how to create a simple test-chain.

**Comment by compleatang** [comment]
Need a new chain?

```
eris chains new CHAINNAME
```

The options for creating a chain are in `eris chains new -h`

To start a chain

```
eris chains start CHAINNAME
```

Need to sync with an existing chain?

```
eris chains install CHAINID
```

The options for installing chains is `eris chains install -h`

**Comment by androlo** [comment]
Great. Thank you. I will play around with this in a little while and update the readme.

**Comment by androlo** [comment]
ah, right. it's just the regular chain creation process...

**Comment by androlo** [comment]
Experimenting with the new eris-cli now. I'll update the README as soon as 0.10.1 is merged to master, which should be today.

**Comment by androlo** [comment]
Installation instructions are pretty clear for eris-cli - just go get and init, so no need to change under installation I think. Under usage I'll add a 'Docker' section which explains how to create and run chains with 'eris-cli' (pretty much what Casey posted here).

**Comment by androlo** [comment]
(and point them to the eris-cli help / docs for more advanced usage)
