### ISSUE TITLE
[Keys] use of experimental, deprecated go-ethereum entropy function

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#333]
@Gustav-Simonsson commented on [Wed Sep 09 2015](https://github.com/eris-ltd/eris-keys/issues/23)

Looks like this function was picked up when forking old go-ethereum code: https://github.com/eris-ltd/eris-keys/blob/master/crypto/randentropy/rand_entropy.go#L32

This function was merely intended as an experiment and to discuss merits of XORing in additional sources onto the OS CSPRNG. It was not intended for production use and has since been removed from the code base since we decided the extra complexity and risks that come with it was not worth potential benefits of additional sources in case the OS source through `crypto/rand` is weak.

Would recommend switching to using plain `crypto/rand` helpers currently used in go-ethereum (these where covered by Ethereum's security audits) : https://github.com/ethereum/go-ethereum/blob/master/crypto/randentropy/rand_entropy.go

---

@ebuchman commented on [Wed Sep 09 2015](https://github.com/eris-ltd/eris-keys/issues/23#issuecomment-138912523)

yup I was following this discussion in go-ethereum. is XORing in this kind of information not a standard practice? were actual risks identified? or was it just "better not add more complexity"? I figured I'd keep it at least as a talking point until I had a better idea why it was removed. Seems like if the host OS generator is compromised (as we've seen it has been a few times), this could be a life saviour.

---

@Gustav-Simonsson commented on [Wed Sep 09 2015](https://github.com/eris-ltd/eris-keys/issues/23#issuecomment-138993881)

Actual, concrete risks where not identified. It was more "better not add more complexity". And yes, if the OS source is compromised it could in theory still achieve enough entropy since it's combined with a hard KDF. Was thinking especially of the issue on android with it's bitcoin wallet.

It was mostly informal discussions though, and most people thought the extra complexity was not worth the potential upside in that case.

I still haven't seen a concrete argument why XORing in additional sources (if weak or even completely manipulated) would weaken the original source from crypto/rand - would be interesting to know of there exists specific attack vectors in that scenario.

**Comment by silasdavis** [comment]
@ebuchman do you have any more thoughts on this?

It seems to me that risk here is if you accidentally mix two correlated sources of entropy. Then you may up with less entropy, take the extreme case `A ^ A` for some byte stream `A`. If the sources are independent, then provided one is statistically random then xoring it won't change the probability of the parity of a bit in the result, it will still be 0.5 for 1 or 0.

The risk of accidentally correlated sources might be enough to make this a bad idea... Also aren't we relying on good PRNG sources, this seems like a rather ad hoc way of mitigating against a bad one...

**Comment by ebuchman** [comment]
Yup probably best to drop it and just use the OS's entropy. That's what eth did too.

**Comment by zramsay** [comment]
can't because of re-license :(
