### ISSUE TITLE
[Logging] Implement coherent consistent logger

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#343]
This logging epic has issues based on the solution outlines of the RFC https://github.com/silasdavis/rfcs/blob/logging/text/0003-logging.md as well as some issues pre-dating the RFC:

| Problem number | Name | Solution outline |
|----------------|------|------------------|
| 1 | Log format | All logging from eris-db should pass through the same (outer) logging library and code path, including logs from dependencies/components. Component logs will be subject to some mapping or embedding within our format. All logging should use a consistent structured format which will be based on something like the Graylog Extensible Log Format (GELF) allowing it to be shipped.|
| 2 | Log structure | Structure logs with consistent metadata including parent context for logs from eris-db components (for example, `[module: rpc/v0, method: broadcast_tx, chain_state: fast_syncing] invalid HEX encoding`, rather than `invalid HEX encoding`).|
| 3 | Log capture | For each dependency we need to centralise the log level, and ideally configure an output adapter that routes through our logging library. This may need a custom component for each different logging library. In the case of dependencies that use a single globabl instance of the go Logger we should use `SetOutput` to capture the output to an io.Writer. |
| 4 | Log output | We should support the at least following logging sinks: stdout, named pipe, files, syslog, and graylog. With a plugin architecture for different sinks (and we will consider fluentd). Each enabled sink will support independent log levels, and where applicable (e.g. for graylog, but not stdout) multiple instances of a logging sink may be configured. |
| 5 | Log volume | We should agree on a standard set and intepretation of log levels and apply this standard to code that we own. For third-party code we should map between a log level set globally and set that level for dependencies. It may make sense to allow the setting of log level per module or hierarchical identifier (see [Log correlation identifiers](#design-ideas)), third party libraries could have all of their logging segregated by such a top-level identifier. We should also allow for the customisation of automatically appended metadata such as datetime format, hostname, log line origin (in source) and verbosity presets can be established for these. |

Tasks from problems 1 - 5 are prefixed with the problem name.

**Comment by benjaminbollen** [comment]
we can build on the "hack" of #349 to pipe components log into a unified logger

**Comment by silasdavis** [comment]
We currently use a tendermint fork of log15 in some places and our own hard fork of logrus. Let's choose one (or something else), and depend on the upstream source rather than fork where possible. If we want to have some formatting or other consistency then I'd much prefer to factor that into some kind of composable unit.

**Comment by zramsay** [comment]
done. specific logging issues are plentiful and well-documented
