### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by ug93tad** [eris-ltd/eris-db#344]
I have the following error (go version is 1.7, docker version 1.12)

# github.com/eris-ltd/eris-db/consensus/tendermint
gohome/src/github.com/eris-ltd/eris-db/consensus/tendermint/local_client.go:36: cannot use (*localClient)(nil) (type *localClient) as type tmspcli.Client in assignment:
	*localClient does not implement tmspcli.Client (missing IsRunning method)
gohome/src/github.com/eris-ltd/eris-db/consensus/tendermint/tendermint.go:125: undefined: proxy.AppConn

NO idea how to fix this

**Comment by benjaminbollen** [comment]
you have to install the new dependency management tool (we have deprecated the use of Godeps); so run

``` go get github.com/Masterminds/glide```

then in the eris-db folder run

```glide install```

then retry building the project with

``` go build ./cmd/eris-db```

**Comment by benjaminbollen** [comment]
Let us know if that solves your problem;  I've opened a new issue to update the readme https://github.com/eris-ltd/eris-db/issues/346
