### ISSUE TITLE
Installing Eris on ARM devices failing

### ISSUE THREAD

**Issue by harshasni007** [eris-ltd/eris-db#345]
I'm getting the following errors when installing Eris on ARM device. Does Eris support ARM devices?
1) sudo apt-get update 
`W: Failed to fetch https://eris-iot-repo.s3.amazonaws.com/eris-deb/dists/DIST/experimental/binary-armhf/Packages  HttpError403`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`

2) sudo apt-get install eris
     `Reading package lists... Done`
     `Building dependency tree ` 
     `Reading state information... Done`
     `E: Unable to locate package eris`

**Comment by zramsay** [comment]
hi @harshasni007, please try the solutions in this issue:
https://github.com/eris-ltd/eris-cli/issues/990

If they do not work, comment in that issue and we'll track there.
