### ISSUE TITLE
[eris-keys] (maybe) import/export issue: https://github.com/eris-ltd/eris-keys/issues/90

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#352]
eris-keys: possible import/export issue: 
for more details see https://github.com/eris-ltd/eris-keys/issues/90

**Comment by j-h-scheufen** [comment]
@silasdavis Can you provide an idea when this problem will be tackled? It's currently preventing us from having 100% of our tests run in CircleCI.
It is reproducible now even without explicitly exporting/importing keys, but only via instantiating a chain from a pre-made config using `--init-dir`.
See branch https://github.com/eris-ltd/eris-contract-bundles/tree/88-library-refactoring
Run: `tests/test.sh`

**Comment by silasdavis** [comment]
@j-h-scheufen it would be helpful if you could provide a more isolated test that clearly demonstrates which part of the system is failing. You are better placed than me to follow the logic of your tests. I am looking into an angle that it may be related to a mismatch in chain name in the genesis and that which is used to start the chain and I will test that when I get the opportunity.

**Comment by j-h-scheufen** [comment]
@benjaminbollen I'm using this ticket to describe the logic of the test.sh script for purposes of recreating the script in a simpler version.

1. Start a new chain from a config in a directory in the repo (/test/chain/bundles_test-full-000)
2. Loop through all "bundle" directories under /src/*
3. For each encountered epm.yaml file, run it with `eris pkgs do` (on the chain started under 1. and using the 'full' account) and collect the result (pass|fail)
4. Report the results of each bundle
5. clean up (remove the chain from 1., stop services, etc.)

FYI: Step number 3. above is intended to be more complex by having more than one epm.yaml per bundle stored in subdirectories under $bundle-dir/test/fixtures/appXY/... However, this is currently blocked by https://github.com/eris-ltd/eris-cli/issues/904

**Comment by zramsay** [comment]
replace by https://github.com/eris-ltd/eris/issues/1133 which is the real issue
