### ISSUE TITLE
Will eris-db ever offer an API that matches ethereum's JSON-RPC specification?

### ISSUE THREAD

**Issue by apmilen** [eris-ltd/eris-db#362]
Big fan of this project, and we would like to integrate it with [dapple](https://github.com/nexusdev/dapple), our solidity developer tool. However, dapple has been developed around Ethereum's [JSON-RPC API](https://github.com/ethereum/wiki/wiki/JSON-RPC) and thus won't work out of the box with [your API specification](https://monax.io/docs/documentation/db/latest/specifications/api/). Do you intend to offer a version of this client with an API built to the Ethereum spec? Sorry if this question has been asked before, I couldn't find any info on the topic. Thanks!

**Comment by AFDudley** [comment]
The short answer is yes.

**Comment by apmilen** [comment]
Cool that's what I was hoping. Is there a timeline for this feature?

**Comment by compleatang** [comment]
Hi @apmilen see issue #331. 

This ticket is asking for the same thing as is noted there so I'm going to close it here and you can follow along with our progress on the other ticket. 

#331 is currently slated for the second sprint of our next release series. So we should have it on develop branch in ~3-5 weeks and fully included in our 0.16.0 release (which will follow our 0.12.0 release coming this week)
