### ISSUE TITLE
[Client] add `mintgen` functionality to create a genesis file

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-db#374]
This is about CLI's requirement to be able to access genesis file generation via the eris-client library.

- from https://github.com/eris-ltd/mint-client/blob/master/mintgen/cli.go
- required for https://github.com/eris-ltd/eris-cli/issues/899

**Comment by silasdavis** [comment]
@zramsay do you literally need every piece of functionality there? Could you give me an overview of the things you need to be able to do? I would just like to be able to understand the bigger picture and see if there if we can improve upon how we encapsulate this functionality and implement.

In particular I've got one eye on how we might want to provide this functionality server-side in a future release.

**Comment by zramsay** [comment]
nope. the `mintgen random` i pulled out of https://github.com/eris-ltd/eris-db/pull/375/files.

**Comment by zramsay** [comment]
note that the `feature_consolidate` branch with mintgen is still a WIP

**Comment by zramsay** [comment]
`mintgen known` takes the filepaths of two csv's (accounts and validators) along with the chainName/chainID and create the genesis file for a chain from known accounts. This functionality was exposed via cli/cm using a roundabout `docker exec` ... but with cm moving into cli, we need another way to access this functionality. cli will be importing some edb packages and can access the function called by `eris-client genesis` (can be renamed) to perform this/

**Comment by zramsay** [comment]
the functionality required by cli is here:
https://github.com/eris-ltd/eris-cli/pull/1072/commits/e3bc509a73cf534a9d8fedf7992f9fce8ae48675
and in edb here (coming from #375):
https://github.com/eris-ltd/eris-db/blob/feature_consolidate/genesis/make_genesis_file.go#L23

**Comment by zramsay** [comment]
also done.
