### ISSUE TITLE
[Eris-Client] Need more descriptive errors

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-db#378]
Since the divorce of tendermint, the entire team has been seeing a lot of these: 

```
Encountered Exception from chain w: %!s(<nil>)
```

We need a way to be more descriptive with the errors.

**Comment by zramsay** [comment]
`confirmation.Error` not type `%s` ... flip to `%v` & it should throw. see also a few lines above
https://github.com/eris-ltd/eris-db/blob/master/client/core/transaction_factory.go#L311
