### ISSUE TITLE
[Logging] Choose a logging library

### ISSUE THREAD

**Issue by silasdavis** [eris-ltd/eris-db#388]
Candidates:

- https://github.com/inconshreveable/log15
- https://github.com/go-kit/kit/tree/master/log
- https://github.com/op/go-logging
- https://github.com/Sirupsen/logrus
- https://github.com/uber-go/zap
- https://github.com/golang/glog

and many more ... http://libs.club/golang/developement/logging

Need to establish some requirements/desirements. Initial thoughts:

- Structured
- Multiple backends (including syslog)
- Pluggable formatters
- Levelled logging
- Multiple output instances at different levels
- Non-global instance

**Comment by silasdavis** [comment]
I am dismissing these candidates:

- https://github.com/op/go-logging
Some nice touches, but ultimately a one-man-show (with some outstanding issues that worry me a bit), with some twiddles that seem nice but could be achieved through more simple composition (instead of AddModuleLevel etc just create a new logger) 

- https://github.com/uber-go/zap
Very fast, and with uber backing it but lacks flexible handlers (https://www.reddit.com/r/golang/comments/4k2k84/zap_fast_structured_leveled_logging_by_uber/) and no syslog support yet. 

- https://github.com/golang/glog
Too simplistic, not structured.

My Shortlist is now:

- https://github.com/inconshreveable/log15
- https://github.com/Sirupsen/logrus
- https://github.com/go-kit/kit/tree/master/log

log15 and logrus seem to be the premier choices for structured logging in go with some maturity (this _is_ go though...). They both allow flexibility with handlers, structured logging, and levels.

One of the maintainers of log15 seems go-kit log as the spiritual successor to log15

**Comment by silasdavis** [comment]
logrus has the highest engagement on github in terms of contributors, commits, and so on. It has many built-in hooks. Log entries refer to a Logger, it seems to have a messier story around routing logs.

go-kit log has a cleaner interface and some thought has been given on how to establish contexts,

It may be possible to combine the logging interface of go-kit log with some of the functionality of logrus. I am planning to wrap all logging calls through our own pinhole logger, so I may be able to hedge my bets here.

**Comment by VoR0220** [comment]
Sounds awesome.
