### ISSUE TITLE
Point mintinfo command to local node.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-db#41]
I want to know what is in the name registry of an eris-db container so I created a shell and ran the following command:

```shell
eris@5e725856816f:~/.eris$ mintinfo names
Post http://pinkpenguin.chaintest.net:46657: dial tcp 128.199.230.153:46657: connection refused
```

I would expect `mintinfo` (and any similar commands) to be configured for the local node by default instead of  `pinkpenguin.chaintest.net`.

**Comment by ebuchman** [comment]
this has been updated to point to localhost in 0.10.3
