### ISSUE TITLE
Resolve naming inconsistency with CLI.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-db#42]
In the CLI, this is a called a "chain".  Here it's called "DB".  This is a confusing inconsistency.

Given that our marketing is promoting that we make it easier to work with blockchains, it makes more sense to me to call this a "chain" as well.  "DB" implies database and a blockchain is not going to meet the expectations of coders who think they're getting a database.

**Comment by compleatang** [comment]
coming soon.
