### ISSUE TITLE
chain starting is running indefinitely without creating the chain

### ISSUE THREAD

**Issue by sathishmanoharan** [eris-ltd/eris-db#432]
Hi,
I am running Eris 0.12.0 version on Ubuntu 14.04. I have run 'eris init' and downloaded the images. 'eris chains make' runs without any error. But when I start the chain, it is running indefinitely with the error. 

Directory missing                 destination=/home/eris/.eris/chains/simplechain
error=Container interactive-e7c1e1b6-9ef2-4f1e-8ef6-ac54c3fc8256 exited with status 1

![image](https://cloud.githubusercontent.com/assets/18713130/21681051/65be36e4-d373-11e6-8c69-b2074e27f24d.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21681071/7a0a16c2-d373-11e6-8ec7-9abfba2111ed.png)
![image](https://cloud.githubusercontent.com/assets/18713130/21681086/96068b62-d373-11e6-8ade-cb33dea25c34.png)

I am behind the corporate proxy and configured /etc/default/docker with proxy details. I am using 'Eris CLI Version: 0.12.0 (002c63e)'. I have given all (777) permission to /home dir. Not sure if this is a problem with directory creation. Could somebody help on this ?

**Comment by benjaminbollen** [comment]
thank you for reporting.  This looks like an issue with the tooling (github.com/eris-ltd/eris-cli) and not the actual blockchain, but should be simple enough to resolve here.  Can you report back what the results are if you run
```
eris chains make tester --chain-type=simplechain
eris chains start tester
eris ls
```
thanks Ben

**Comment by sathishmanoharan** [comment]
Hi @benjaminbollen , 

I am still getting the same error. 

![image](https://cloud.githubusercontent.com/assets/18713130/21683678/6a8b42fe-d380-11e6-9c05-20a7e787117b.png)

Can you please let me know if there is a workaround for this?

**Comment by benjaminbollen** [comment]
Can you try running `eris clean -ya` before (WARNING, will wipe your `.eris` folder).  Perhaps there are lingering docker containers from an earlier version of eris.

**Comment by sathishmanoharan** [comment]
Hi @benjaminbollen , Thanks for your reply. I cleaned .eris and uninstalled eris and docker and installed them again. But I am still getting the same error. One thing i noticed while running the 'eris chains start' command is that, eris keys image is picking the tag 'latest' instead of '0.12.0'. I am running this without docker-machine.
![image](https://cloud.githubusercontent.com/assets/18713130/21720578/fad604e2-d449-11e6-8184-b7d243224bbe.png)

I ran the 'chains start' command twice and it has created 2 'eris data' containers. But they are not in running status. Can you please help in resolving this issue?
![image](https://cloud.githubusercontent.com/assets/18713130/21720495/8186b50a-d449-11e6-8d81-9979d4a800cf.png)

**Comment by zramsay** [comment]
@sathishmanoharan when creating a chain for the first time, the `--init-dir` flag is required on `eris chains start`. After that, you can `start | stop` your chain without the flag. However, if you remove both the chain and its data container then you'll need the `--init-dir` flag again.

**Comment by sathishmanoharan** [comment]
Hi, @zramsay, I tried init-dir flag. But I am getting the same error. I was able to start the chain in windows 10 without the init-dir flag. Can you please look into this issue?

![image](https://cloud.githubusercontent.com/assets/18713130/21757858/d0f37ca0-d65a-11e6-826e-8dc769804c81.png)

**Comment by benjaminbollen** [comment]
Hi @sathishmanoharan,

Im sorry to find this is not resolved for you; can we outline the reproducible environment ?  You are working on ubuntu 14.04 (linux) (and the problem is not occuring on Windows 10 - referenced above), correct?

Can you try either an absolute path; or otherwise start the relative path from `./eris/chains/`, ie just try
```
eris chains make tester2 --chain-type=simplechain
eris chains start tester2 --init-dir=tester2
eris ls
eris chains logs -f tester2
```
Hope that helps
Ben

**Comment by sathishmanoharan** [comment]
Hi @benjaminbollen , Thanks for your reply. I was able to resolve this error today. I had to run the 'eris data rm' command to remove all the data containers. (there were few 'keys' and 'chain-name' containers). Then I started the chain using 'eris chains start' and it started fine. I haven't deployed the contracts to the chains yet. I will try that tomorrow. Hopefully it should be fine. 
I followed the steps in the tutorial. Are you able to infer what is going wrong with this information?

**Comment by benjaminbollen** [comment]
Glad you got this hurdle cleared.  I tried reproducing but without success.  It is possible that old containers failed to get cleared and clogged the creation of the new chain.  We have the issue logged for future reference to get to reproducibility.

You may additionally get help from our community on slack.monax.io if you encounter any problems with the contract tutorials.
