### ISSUE TITLE
[consolidation] genesis make

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#434]
work on `unstable-develop` `genesis/` to rework genesis make for eris-cli consolidation (porting `mintclient gen`)

**Comment by benjaminbollen** [comment]
checklist:
- [x] refactor eris-db genesis types
- [ ] refactor functionality without changing behaviour but to allow for planned new features
- [x] replace marmot time with genesis time
- [x] prepare for correction of ChainId versus ChainName
- [ ] introduce canonical order for genesis bytes to allow for derived ChainId = Hash(GenesisDoc)
- [ ] allow Monax SDK deployment through genesis

**Comment by zramsay** [comment]
this issues purpose has been outlived
