### ISSUE TITLE
branches need to be cleaned up

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#45]
there are **way** too many hanging branches in this repository. 

once the refactor is complete in tmnt branch then we need to remove / merge / clean up all of these branches and adhere to our coding practices...

feature -> (develop) -> staging -> master

**Comment by ebuchman** [comment]
ok. I'm gonna just drop all the old "stale" stuff that hasn't been touched in months.

**Comment by ebuchman** [comment]
much nicer. not sure what the deal is with project_bruno branch or develop. I've been based off 0.10.3. Thats what tmsp and 0.10.4 branches are based on. 0.10.4 is just support for eris-keys signing for consensus. may we roll 0.10.3 into 0.11, and shoot for the 0.12 release being just supporting the eris-keys signing for validators (that will involve most elements of the stack harmonizing on fixing their tests to use that). Then we can go back to the refactor. Thoughts?
