### ISSUE TITLE
[feature] automated timer transaction

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-db#512]
This one is a simple snative to implement i would think. Setting a timer for a transaction to be executed with a signature. Someone tell me what im missing in making this a reality?

**Comment by VoR0220** [comment]
To clarify this would be thought of as a scheduled contract execution based on time/date and should be accurate to within 2 seconds.

**Comment by benjaminbollen** [comment]
This does not sound to me like a a secure native function; rather with future work on the light-client, eris-worker, we can consider (time) triggered transaction (creation and broadcast). Snative functions are of no more help here than normal evm executions, in that they cannot pause or self-initiate.
