### ISSUE TITLE
on eris chains new NAME --dir PATH chain_id in genesis.json is overwritten by NAME

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db#52]
Following the tutorial I constructed a genesis.json by hand. when creating a new chain from it the chain_id was over written.

Proof:

Snippet of genesis.json:
```
{
  "chain_id": "simple_chain",
  "accounts": [
    {
      "address": "8C3A4A59FC07EA11433340D3B18F852EBD8DCA16",
      "amount": 690000000000
    },
```

and snippet of the output from localhost:46657/genesis
```
{"jsonrpc":"2.0","id":"","result":[17,{"genesis":{"genesis_time":"2016-01-21T01:24:35.082Z","chain_id":"simplexD","params":null,"accounts":[{"address":"8C3A4A59FC07EA11433340D3B18F852EBD8DCA16","amount":690000000000,"name":"","permissions":null},
```

**Comment by ebuchman** [comment]
i believe the idea here is you can easily create more chains with the same accounts/validators but different names by always specifying the name on the command line
