### ISSUE TITLE
Consider moving RPC library into client package

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-db#527]
We should have a base "standard" RPC, that can be made extensible to RPC vectors such as tendermint, or web3, and this should either be directed by the client, or the rpc library itself (converge into the base calls of the client). Currently, it's a bit messy and fairly confusing to navigate, and nesting could help to alleviate this.

**Comment by benjaminbollen** [comment]
A lot of work needs to be done on the RPC.  The proposal of an extensible RPC is good and taken onboard.  eris-db needs to incorporate a secure writing api under `eris-worker` (currently only exposed through tooling or js libs).

I strongly disagree that nesting packages solves any of the current hurdles, nor do I read an argument to support it.  From that I think it is safe to close this issue.

**Comment by VoR0220** [comment]
Nesting can alleviate me having to jump around the entire DB to figure out how things are all connected, it's just another depth inward, and could fit under the "rpc" package that has been set up under the client (which I would think would be a sensible thing to do?) Overall this needs to all be cleaned up, currently it's very difficult to navigate and very difficult to figure out wtf is going on.

**Comment by benjaminbollen** [comment]
rpc is not a child of client;
golang favors a flat tree structure much more than a nested one

**Comment by VoR0220** [comment]
https://github.com/eris-ltd/eris-db/tree/master/client/rpc

**Comment by benjaminbollen** [comment]
I am aware of the renaming that happened; I cannot say that I think that is a good renaming as it happened, but I as everyone else pick my battles; but importantly that is not the rpc package you are referring to.
