### ISSUE TITLE
improve name reg

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#57]
- permanent names
- contract guarded names
- multisig

**Comment by benjaminbollen** [comment]
can we detail the intention here, and the desired timeline?

**Comment by ebuchman** [comment]
intention here is to clear some cumbersomeness with the namereg. currently names expire based on how much funds you register with, which is annoying, so we should have permanent names. we also, presumably, want names that can be owned by contracts or managed by multisig. there's no priority on this, its just something to bring in down the road once other pieces have settled

**Comment by compleatang** [comment]
will revisit in preparation for hardening for 1.0

**Comment by silasdavis** [comment]
@compleatang @benjaminbollen Is this issue worth keeping around, I feel like when it becomes relevant many other things may have moved and I'd like to reduce clutter in the issues?
