### ISSUE TITLE
[EVM] Changes to suicide behaviour

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#58]
https://github.com/tendermint/tendermint/issues/98

really, sync with eth.

**Comment by compleatang** [comment]
@ebuchman can you confirm whether you will be able to close this issue before the end of the month? otherwise we will reassign to Ben or Silas.

**Comment by ebuchman** [comment]
happy to stay assigned whether or not I finish by months end. this should be synced with the ethvm work

**Comment by VoR0220** [comment]
Keep an eye out, this name has since been changed in solc to selfdestruct...the opcode is on course to change as well IIRC

**Comment by silasdavis** [comment]
@ebuchman could you elaborate on what the outcome of this ticket was intended to be?

**Comment by silasdavis** [comment]
eris-db contains the changes in vm.go referenced here: https://github.com/tendermint/tendermint/pull/133/files
