### ISSUE TITLE
cleanup these branches

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#61]

**Comment by benjaminbollen** [comment]
following branches are stale and have no unmerged commits  - will remove tomorrow evening (17 CET)

- [ethans fixes](https://github.com/eris-ltd/eris-db/tree/ethansfixes)
- [project bruno](https://github.com/eris-ltd/eris-db/tree/project_bruno)

two branches are fixes by @ebuchman  from project genesis
- [disable IP cap](https://github.com/eris-ltd/eris-db/tree/disable_ip_caps) - exclusive godeps/ quick fix; do we want the limit revoked ?
- [fixes](https://github.com/eris-ltd/eris-db/tree/fixes) - common root for genesis p2p handshake has been added to eris-db/godep/tmint in ethvm branch; should this also be ported to tmint/tmint; tmint/go-p2p ? @ebuchman does this have other fixes from genesis?

not sure who committed this (@dennismckinnon ?)
- [updateState](https://github.com/eris-ltd/eris-db/commit/40a6546b60dd9021564ebc98c7fb69aab9464e8a#diff-78d9256fa9145e403e8cb7aad542b9a5R80) not sure whether this is a legitimate update

@ebuchman is the work from these included elsewhere or part deprecated?
- [tmsp](https://github.com/eris-ltd/eris-db/tree/tmsp)
- [mempool](https://github.com/eris-ltd/eris-db/tree/mempool)

**Comment by compleatang** [comment]
can you push a tag for project bruno (think there's still some code running which uses that, but better a tag than a branch)

**Comment by benjaminbollen** [comment]
pushed tag and removed branch `project_bruno`

**Comment by ebuchman** [comment]
ok, i deleted `ethansfixes`, `mempool`, `lessLogs`, and `disableipcaps`.

`updateState` is being used by dennis right now, lets leave that. It has some changes we might want to merge to mint-client/mintdump instead.

`fixes` has the project genesis fixes and some other stuff. i'll merge it this week for the 0.11.3 release.

`ethvm` is branched from `fixes`. it will be the branch for 0.11.4 (hopefully!) and will include geth's vm (hopefully you can help out getting it there).

`tmsp` I'm targeting for 0.12.0, which should align with `eris chains` refactor. It will inherit things like the `ethvm` and other fixes going into the 0.11 series, but by the time we're using tmsp all the peer/consensus stuff will be in tendermint core (or whatever other consensus erisdb plugs into), so many of the fixes made to erisdb are already replicated there  (ill compile a short list of what's missing - ie. p2p handshake with genesis state root).

Hope that helps.

**Comment by benjaminbollen** [comment]
Thanks !
