### ISSUE TITLE
Implement go-ethereum EVM

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#72]

**Comment by silasdavis** [comment]
@benjaminbollen @compleatang capturing what we decided in Berlin WRT to this:

* Fork Ethereum to allow changes or track upstream as we wish
* Update eris/tendermint to match the [godeps vendored tendermint in eris/eris-db](https://github.com/eris-ltd/eris-db/tree/master/Godeps/_workspace/src/github.com/tendermint)
* Sync the vendored version of tendermint with eris/tendermint
* Pull up the tendermint repository to the top level of this repository
* Make tests pass
* Factor out some of the tendermint/* stuff then pull tendermint/tendermint to top level
* Make tests pass
* Make eris-db depend on appropriate packages in eris/ethereum (for current VM)
* Remove [old tendermint VM](https://github.com/eris-ltd/eris-db/tree/master/Godeps/_workspace/src/github.com/tendermint/tendermint/vm)
* Manually apply work-in-progress unforking changes from #69 
* Complete unforking of Ethereum VM so eris/eris-db/tendermint depends on current Ethereum VM as a proper dependency

**Comment by AFDudley** [comment]
How are we planning to address ed22519 support in the unforked EVM?

**Comment by silasdavis** [comment]
@AFDudley I don't know, could you elaborate? Assuming we have some patched ed22519 support in currently eris-db -> vendored tendermint -> 'forked' eth?

**Comment by AFDudley** [comment]
Yeah. That's the assumption, I don't have the details, but it should be trivial to check by looking at imports.

**Comment by silasdavis** [comment]
With erismint and other priorities consider this superceded and ticket not needed to remind us that this is a thing, let's create another ticket before we embark on such integration.
