### ISSUE TITLE
collapse and reconcile mint-client tooling into the eris chains binary/repository

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#75]
not sure if they should be the exact same binary, but at least they should be collapsed into this repository for coherence. the mint-client tooling needs to then be refactored (post rpc reconciliation process) so that it is low level go libs for "using" eris chains

**Comment by ebuchman** [comment]
lets have a `tools` dir in erisdb and we can move them all there and drop the `mint` prefixes. not sure if it needs to be in the binary either, might be nice to keep the binary as just a server and the low level tooling separate
