### ISSUE TITLE
move all env vars used to respect the `ERISDB_` prefix

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#77]

**Comment by benjaminbollen** [comment]
Currently all environment variables are being ported to `ERIS_DB_*`;
I have to integrate environment variables from the shell scripts into the `eris-db` command, and I will transition for 0.12.0-rc2 both versions of the ENV (with and without prefix); then deprecate the without prefix

**Comment by compleatang** [comment]
This is done, no?

**Comment by benjaminbollen** [comment]
yes
