### ISSUE TITLE
reconcile config files

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#81]
currently we have too many config files. And we haven't even started moving to the consensus+app separation. config files will be reduced by closing #70 and better reliance on env vars (which will give the cli more fine tuneable control over boot configuration). 

per @AFDudley we should be thinking of large config files which can `include` other config files. in general we need to be smarter about our strategy here.

**Comment by benjaminbollen** [comment]
this is probably a topic worth discussing and getting right when we sit together later in the week; I can look to prepare a proposal

**Comment by compleatang** [comment]
this can be closed.
