### ISSUE TITLE
ensure that **all** signing happens via eris-keys

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#86]
somewhat blocking on tmint here.

**Comment by ebuchman** [comment]
this should just be a config option for erisdb: https://github.com/eris-ltd/eris-db/blob/master/erisdb/serve.go#L69

Is there something else? 

We should make it a bit more robust - right now if the http con to keys fails itll panic, should retry a few times instead

**Comment by compleatang** [comment]
Great. Anyway we just need to have that as our default rather than the current system. Does tmint still need the priv_validator.json in what we're using and/or on current (TMSP based) master?

**Comment by ebuchman** [comment]
Neither!

**Comment by ebuchman** [comment]
Though, the expectation for now is that consumers using their own keys system should fork tendermint to make the appropriate changes in the node/node.go file

**Comment by compleatang** [comment]
Where do we set the right public key to use for signing?

**Comment by ebuchman** [comment]
right. so currently the strategy is to use a priv_validator.json but without the privkey! we should probably just make that another config option tho instead and do away with that file completely? That file is useful tho to prevent double signing - if we get rid of it, we should have at least something to take its place

**Comment by compleatang** [comment]
Cool. So the plan from the tmint side is to use priv vals but to remove the private key string from the priv val and when it talks to the signer it will be using the pub key in the priv Val. 

Is that right?

**Comment by ebuchman** [comment]
We don't have an explicit plan as of yet for what to do about keys. I made those changes to easily support eris-keys, but tendermint is still using full on priv_validator.json. Might be worth seeing if the Ledger guys can incorporate some rule based system somehow for what not to sign, and then ideally we can adopt that too.

**Comment by silasdavis** [comment]
The essence of this is still relevant, but I think we have a clear idea about the future of keys that has moved on from this.
