### ISSUE TITLE
update docker version in circle.yml to 1.10 or above

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-db#93]

**Comment by AFDudley** [comment]
Naively bumping the version breaks the "-e lxc" flag in the ubuntu upstart script. sed patching around that returns a new error regarding docker failing to load its apparmor profile.

I assume the cirlceci patch is incompatible with the ubuntu version we are using. Ben says the priority is low, so I'm not looking into it further

Citations:
https://github.com/docker/docker/pull/17700
https://github.com/docker/docker/issues/15340
https://github.com/docker/docker/issues/21505

**Comment by AFDudley** [comment]
@NodeGuy are you working on a fix for this?

**Comment by benjaminbollen** [comment]
@AFDudley is this worth revisiting now with the alpine base image?

**Comment by NodeGuy** [comment]
@AFDudley Sorry, I didn't see your April comment until now for some reason.  No, I'm not working on Eris DB.
